#!/usr/bin/env python
"""
Publish the most recent generated project to GitHub
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from github import Github
from datetime import datetime

# Load environment variables
load_dotenv()

def find_latest_project():
    """Find the most recently generated project"""
    output_dir = Path("output")
    
    if not output_dir.exists():
        print("❌ No output directory found")
        return None
    
    # Find all project directories
    all_projects = []
    for project_folder in output_dir.iterdir():
        if project_folder.is_dir():
            for timestamp_folder in project_folder.iterdir():
                if timestamp_folder.is_dir():
                    all_projects.append((timestamp_folder.name, timestamp_folder))
    
    if not all_projects:
        print("❌ No projects found in output directory")
        return None
    
    # Sort by timestamp and get the latest
    all_projects.sort(reverse=True)
    latest = all_projects[0][1]
    
    print(f"📁 Found latest project: {latest}")
    return latest

def publish_to_github(project_dir):
    """Publish project to GitHub"""
    
    from pathlib import Path
    
    # Convert to Path if string
    project_dir = Path(project_dir)
    
    # Get GitHub token
    github_token = os.getenv("GITHUB_TOKEN")
    if not github_token:
        print("❌ GITHUB_TOKEN not found in .env file")
        return False
    
    print(f"✅ GitHub token loaded (length: {len(github_token)})")
    
    try:
        # Initialize GitHub
        g = Github(github_token)
        user = g.get_user()
        print(f"✅ Authenticated as: {user.login}")
        
        # Create repository name from project folder
        repo_name = project_dir.parent.name
        description = f"Edge-optimized real-time anomaly detection for Industrial IoT - Generated by Auto-GIT on {datetime.now().strftime('%Y-%m-%d')}"
        
        print(f"\n📦 Creating repository: {repo_name}")
        
        # Create repository
        repo = user.create_repo(
            name=repo_name,
            description=description,
            private=False,  # Change to True if you want private repo
            auto_init=False
        )
        
        print(f"✅ Repository created: {repo.html_url}")
        
        # Upload files
        print("\n📤 Uploading files...")
        
        for file_path in project_dir.glob("*"):
            if file_path.is_file():
                filename = file_path.name
                content = file_path.read_text(encoding="utf-8")
                
                try:
                    repo.create_file(
                        path=filename,
                        message=f"Add {filename}",
                        content=content
                    )
                    print(f"  ✅ Uploaded: {filename}")
                except Exception as e:
                    print(f"  ❌ Failed to upload {filename}: {e}")
        
        print(f"\n🎉 Success! Repository published at:")
        print(f"   {repo.html_url}")
        
        return True
        
    except Exception as e:
        print(f"\n❌ Error: {e}")
        return False

if __name__ == "__main__":
    print("="*60)
    print("📤 Auto-GIT GitHub Publisher")
    print("="*60)
    print()
    
    # Find latest project
    project_dir = find_latest_project()
    if not project_dir:
        exit(1)
    
    # List files to be published
    files = list(project_dir.glob("*"))
    print(f"\n📄 Files to publish ({len(files)}):")
    for f in files:
        if f.is_file():
            print(f"  • {f.name}")
    
    # Confirm
    print()
    response = input("📤 Publish to GitHub? [Y/n]: ").strip().lower()
    if response and response not in ['y', 'yes']:
        print("❌ Publishing cancelled")
        exit(0)
    
    # Publish
    print()
    success = publish_to_github(project_dir)
    
    if success:
        print("\n✅ All done!")
    else:
        print("\n❌ Publishing failed")
        exit(1)
